services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    networks:
      spsnet:
        ipv4_address: 10.0.5.201
    restart: unless-stopped
    # environment:
    #  S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file
    #  PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
    #  PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    #  XDG_RUNTIME_DIR: /tmp # Path for pipewire
    # devices:
    #   - "/dev/snd" # ALSA device, omit if using PulseAudio
    volumes:
      - ${PWD}/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
      - ${PWD}/owntone/mnt/media:/srv/music # Pipe for audio output
    #   - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
    #   - /run/user/1000/pipewire-0:/tmp/pipewire-0 # Pipewire socket when using pipewire
    # command: -o pw # You can specify the desired output with command:
    logging:
      options:
        max-size: "200k"
        max-file: "10"

  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: OwnTone
    network_mode: host
    devices:
      - "/dev/snd"
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ${PWD}/owntone/etc/owntone:/etc/owntone
      - ${PWD}/owntone/mnt/media:/srv/media
      - ${PWD}/owntone/var/cache/owntone:/var/cache/owntone
    restart: unless-stopped

networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      # this is the hardware network interface of the docker host (ifconfig)
      parent: eth0
    ipam:
      config:
          # this is the subnet on which the docker host resides
          # set in a range outside of the primary DHCP server
        - subnet: 10.0.5.0/24
          # this is the IP address of the docker host
          gateway: 10.0.5.101